config/routes.rb
Merikotkat::Application.routes.draw do
  get 'visitation_forms/search' => 'visitation_forms#search'
  get "api/getringer"
  get "api/getmunicipalities"
  get "api/getspecies"
  get "api/getcolors"
  resources :visitation_forms

  resources :external_authentication, controller: 'koala_client/external_authentication'

  get "logout" => 'koala_client/external_authentication#logout'

  get "welcome/index"

  root 'welcome#index'

  resources :images
  get 'visitation_forms/birds/create' => 'visitation_forms#create_bird'
  get 'visitation_forms/birds/delete' => 'visitation_forms#delete_bird'
  get 'visitation_forms/approve/:id' => 'visitation_forms#approve_form'
  get 'visitation_forms/unsubmit/:id' => 'visitation_forms#unsubmit_form'
  get 'visitation_forms/submit/:id' => 'visitation_forms#submit_form'
  get 'visitation_forms/list/:type' => 'visitation_forms#index'
  get 'visitation_forms/delete/:id' => 'visitation_forms#destroy' , as: 'destroy_visitation_form'

  get 'images/delete/:id' => 'images#delete'
  get 'images/delete/' => 'images#delete'
  get 'images/thumbnail/:id' => 'images#thumbnail'
  get 'images/thumbnail/' => 'images#thumbnail'

  get 'external_api' => 'external_apis#index'
  get 'external_api/getimageurls/:id' => 'external_apis#getimageurls'
  get 'external_api/getvisitationforms/' => 'external_apis#getvisitationforms'
  get 'external_api/getimage/:id' => 'external_apis#getimage'

  get '*hurrdurr' => 'application#render_404'

end

app/controllers/visitation_forms_controller.rb
class VisitationFormsController < ApplicationController
  before_action :set_visitation_form, only: [:show, :edit, :update, :destroy, :submit_form, :unsubmit_form, :approve_form]
  before_action :check_permission, except: [:index, :search, :new, :create, :add_owners]
  before_action :set_municipalities_api
  before_action :set_images, only: [:show, :edit, :new]

  def set_municipalities_api
    if Rails.env.test?
      @tipuapi = TipuApiHelperMock
    else
      @tipuapi = TipuApiHelper
    end
  end

  def set_images
    @young_images = Image.get_young_images(params[:id])
    @landscape_images = Image.get_landscape_images(params[:id])
    @nest_images = Image.get_nest_images(params[:id])
  end


  # GET /visitation_forms
  # GET /visitation_forms.json
  def index
    # Filter the forms
    if (defined? params[:type] and !params[:type].nil?)
      @header = t(params[:type])
      @type = params[:type]

      if ((defined? params[:sortby] and !params[:sortby].nil?) and defined? params[:order] and !params[:order].nil?)
        @sortby = params[:sortby]
        @order = params[:order]
      else
        @sortby_order = ""
        params[:sortby] = nil
        params[:order] = nil
      end

      if (@visitation_forms = VisitationForm.get_forms_of_type @user, params[:type], params[:sortby], params[:order], nil, nil, nil, nil, nil, nil) == false
        not_found
      end
    else
      @visitation_forms = Array.new
    end

    @total_visitation_forms = @visitation_forms.count

    if Rails.env.test?
      @per_page = 5
    else
      @per_page = 15
    end

    @pages = (@total_visitation_forms.to_f / @per_page.to_f).ceil
    @current_page = params[:page].nil? ? 1 : params[:page].to_i

    if (not defined? params[:page] or params[:page].nil?)
      @visitation_forms = @visitation_forms.first(@per_page)
    else
      start_index = (params[:page].to_i - 1) * @per_page
      end_index = start_index + @per_page - 1
      @visitation_forms = @visitation_forms[start_index..end_index]
    end
  end

  def search
    @nestid = params[:nestid]
    @nestname = params[:nestname]
    @speciesid = params[:speciesid]
    @datefrom = params[:datefrom]
    @dateto = params[:dateto]
    @photographername = params[:photographername]

    if @user[:type] == 'admin'
      params[:type] = 'archive' if params[:type].nil?
    else
      params[:type] = 'unsubmitted' if params[:type].nil?
    end

    @type = params[:type]
    if @nestid.nil? && @nestname.nil? && @speciesid.nil? && @datefrom.nil? && @dateto.nil? && @photographername.nil?
      @visitation_forms = []
    else
      @visitation_forms = VisitationForm.get_forms_of_type @user, @type, nil, nil, @nestid, @speciesid, @datefrom, @dateto, @nestname, @photographername
    end
  end

  # GET /visitation_forms/1
  # GET /visitation_forms/1.json
  def show

  end

  # GET /visitation_forms/new
  def new
    @uuid = SecureRandom.uuid
    @visitation_form = VisitationForm.new
    @visitation_form.save :validate => false
    @visitation_form.species_id = 'HALALB'  # set merikotka as default...
    @visitation_form.birds << Bird.new
    @visitation_form.owners << Owner.new(owner_name: @user[:user_name], owner_id: @user[:login_id])
    update_audit_log 'create'
  end

  # GET /visitation_forms/1/edit
  def edit
    if @visitation_form.approved
      redirect_to @visitation_form
    else
      @uuid = SecureRandom.uuid

    end
  end

  # POST /visitation_forms
  # POST /visitation_forms.json
  def create
    @visitation_form = VisitationForm.new(visitation_form_params)
    save_form
  end

  # PATCH/PUT /visitation_forms/1
  # PATCH/PUT /visitation_forms/1.json
  def update
    @visitation_form.attributes = visitation_form_params
    save_form
  end

  def create_bird
    bird = Bird.new
    bird.visitation_form_id = params[:form_id]
    bird.save
    render json: { bird_id: bird.id }
  end

  def delete_bird
    bird = Bird.find(params[:bird_id])

    # delete all images attached to the bird
    bird.images.each do |img|
      img.destroy
    end

    bird.destroy
    render json: {status: "ok" } and return
  end

  def save_form
    @visitation_form.sent = false

    @visitation_form.approved = false if @visitation_form.approved == nil

    destroy_deleted_images

    add_owners params[:owners], @visitation_form.id
    update_birds params[:birds], @visitation_form
    #attach_images params[:visitation_form][:uuid], @visitation_form

    # save with validation if needed.
    if @visitation_form.save :validate => params[:save].nil?
      # mark form as 'sent' if needed
      if params[:submit]
        @visitation_form.sent = true
        # look, another save!
        @visitation_form.save
        update_audit_log 'submit_form'
      else
        update_audit_log 'update'
      end

      redirect_to @visitation_form
    else
      @young_images = Image.get_young_images(params[:id])
      @landscape_images = Image.get_landscape_images(params[:id])
      @nest_images = Image.get_nest_images(params[:id])
      render action: 'new'
    end
  end

  def approve_form
    if @user[:type] == 'admin'
      @visitation_form.sent = true
      @visitation_form.approved = true
      @visitation_form.save :validate => false
      update_audit_log
    end
    redirect_to @visitation_form
  end

  def submit_form
    @visitation_form.sent = true
    if @visitation_form.save
      update_audit_log
      redirect_to @visitation_form
    else
      render action: 'edit'
    end
  end

  def unsubmit_form
    @visitation_form.sent = false
    @visitation_form.save validate: false
    update_audit_log
    redirect_to @visitation_form
  end


  # DELETE /visitation_forms/1
  # DELETE /visitation_forms/1.json
  def destroy
    if @visitation_form.images.count > 0
      flash[:notice] = I18n.t('form_has_images')
      redirect_to @visitation_form and return
    end

    @visitation_form.destroy
    update_audit_log
    respond_to do |format|
      format.html { redirect_to action: 'index', :type => "unsubmitted" }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def check_permission
    unless user_has_access_to_form @visitation_form
      not_found
    end
  end

  def user_has_access_to_form form
    return true if @user[:type] == 'admin'

    form.owners.each do |owner|
      return true if owner.owner_id == @user[:login_id]
    end

    return true if form.photographer_id == @user[:login_id]

    return false
  end

  def update_audit_log action = action_name
    entry = AuditLogEntry.new
    entry.timestamp = Time.now
    entry.userid = @user[:login_id]
    entry.username = @user[:user_name]
    entry.visitation_form_id = @visitation_form.id
    entry.operation = action
    entry.save
  end


  def set_visitation_form
    @visitation_form = VisitationForm.find(params[:id])
  end

  def update_birds(bird_array, form)
    bird_array.each do |bird_info|
      bird = Bird.find(bird_info[:id])
      bird.shyness = bird_info[:shyness]
      bird.gender = bird_info[:gender]
      bird.ringed = bird_info[:ringed]
      bird.gender_determination_method = bird_info[:gender_determination_method]
      bird.left_ring_code = bird_info[:left_ring_code]
      bird.left_ring_color = bird_info[:left_ring_color]
      bird.right_ring_code = bird_info[:right_ring_code]
      bird.right_ring_color = bird_info[:right_ring_color]
      bird.save
    end
  end

  def add_owners(owner_array,formId)
    Owner.where("visitation_form_id = ?", formId).destroy_all
    owner_array.each do |owner_info|
      owner = Owner.new
      owner.owner_name=owner_info[:name]
      owner.owner_id=owner_info[:id]
      @visitation_form.owners << owner
    end
  end

  def attach_images(uuid, form)
    images = Image.where "upload_id = ?", uuid
    images.each do |img|
      img.visitation_form_id = form.id
      img.upload_id = NIL
      img.save
    end

    i = 0
    form.birds.each do |bird|
      images.select { |img| img.temp_index == i }.each do |image|
        image.bird_id = bird.id
        img.visitation_form_id = form.id
        image.save
      end
      i += 1
    end
  end

  def destroy_deleted_images
    if params[:deleted_images] != nil
      params[:deleted_images].each do |img_id|
        Image.find(img_id).destroy
      end
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def visitation_form_params
    params.require(:visitation_form).permit(:photographer_name, :visit_date, :camera, :lens, :teleconverter, :municipality, :nest, :nest_id, :photographer_id, :species_id, :additional_info, :gender_determination_method, :ringed)
  end
end

app/helpers/visitation_forms_helper.rb
module VisitationFormsHelper
end

app/views/visitation_forms/edit.html.erb
<h1><%= t('edit_visitation_form') %></h1>

<%= render 'form' %>

app/views/visitation_forms/index.html.erb
<h1><%= @header %></h1>



<div id="pagination">

</div>

<div class="clear"></div>

<table id="formList">
  <thead>
    <tr>
      <th>
        <%= t('nest_id', scope: [:activerecord, :attributes, :visitation_form]) %>
        <div>
          <%= create_link "&#9650;", "nest_id", "desc" %> <%= create_link "&#9660;", "nest_id", "asc" %>
        </div>
      </th>
      <th>
        <%= t('nest', scope: [:activerecord, :attributes, :visitation_form]) %>
        <div>
          <%= create_link "&#9650;", "nest", "desc" %> <%= create_link "&#9660;", "nest", "asc" %>
        </div>
      </th>
      <th>
        <%= t('visit_date', scope: [:activerecord, :attributes, :visitation_form]) %>
        <div>
          <%= create_link "&#9650;", "visit_date", "desc" %> <%= create_link "&#9660;", "visit_date", "asc" %>
        </div>
      </th>
      <th>
        <%= t('photographer_name', scope: [:activerecord, :attributes, :visitation_form]) %>
        <div>
          <%= create_link "&#9650;", "photographer_name", "desc" %> <%= create_link "&#9660;", "photographer_name", "asc" %>
        </div>
      </th>

      <% if @visitation_forms.count > 0 %>
          <th></th>
          <th></th>
      <% end %>
    </tr>
  </thead>




  <tbody>
    <% @visitation_forms.each do |visitation_form| %>

      <tr>
        <td class="nestid"><%= visitation_form.nest_id  %></td>
        <td class="nestname"><%= visitation_form.nest %></td>
        <td class="visitdate"><%= visitation_form.visit_date.strftime("%d.%m.%Y")  unless visitation_form.visit_date.nil?  %></td>
        <td class="photographer"><%= visitation_form.photographer_name %></td>

        <% if @visitation_forms.count > 0 %>
            <td><%= link_to t('show'), visitation_form %></td>
            <% if @type.nil? || @type == "unsubmitted" %>
                <td><%= link_to t('edit'), edit_visitation_form_path(visitation_form) %></td>
            <% else %>
                <td></td>
            <% end %>
        <% end %>
      </tr>

  <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new_visitation_form'), new_visitation_form_path %>

<script>
  $(function() {
      <% if @pages > 1 %>
        <% if @current_page > 1 %>
            var link = '<%= create_pagination_link "<<", (@current_page.to_i-1), @sortby, @order %>'
            $("#pagination").append(link);
        <% end %>

        <% for i in 0...@pages %>
          <% if (i+1) == @current_page %>
            $("#pagination").append('<div id="pagination-active">' + (<%=i%>+1) + '</div>');
          <% else %>
            var link = '<%= create_pagination_link (i+1).to_s, (i+1), @sortby, @order %>'
            $("#pagination").append(link);
          <% end %>
        <% end %>

        <% if @current_page < @pages %>
            var link = '<%= create_pagination_link ">>", (@current_page.to_i+1), @sortby, @order %>'
            $("#pagination").append(link);
        <% end %>
      <% end %>

  });
</script>

app/views/visitation_forms/new.html.erb
<h1><%= t('new_visitation_form') %></h1>

<%= render 'form' %>

app/views/visitation_forms/search.html.erb
<form method="get" id="searchform">
  <table>
    <tr>
      <td><%= t("activerecord.attributes.visitation_form.photographer_name") %></td><td><input type="text" name="photographername" value="<%= @photographername %>" /></td>
    </tr>
    <tr>
      <td><%= t("activerecord.attributes.visitation_form.nest_id") %></td><td><input type="text" name="nestid" value="<%= @nestid %>" /></td>
    </tr>
    <tr>
      <td><%= t("activerecord.attributes.visitation_form.nest") %></td><td><input type="text" name="nestname" value="<%= @nestname %>" /></td>
    </tr>
    <tr>
      <td><%= t("activerecord.attributes.visitation_form.species_id") %></td><td><input type="text" name="speciesid" id="speciesid" value="<%= @speciesid %>" /></td>
    </tr>
    <tr>
      <td><%= t('date_from') %></td><td><input type="date" name="datefrom" value="<%= @datefrom %>" /></td>
    </tr>
    <tr>
      <td><%= t('date_to') %></td><td><input type="date" name="dateto" value="<%= @dateto %>" /></td>
    </tr>
    <tr>
      <td></td>
      <td>
        <% if @user[:type] == 'admin' %>
            <%= select_tag "type", options_for_select([ [t('unsubmitted'), 'unsubmitted'], [t('submitted'), 'submitted'], [t('archive'), 'archive'] ], @type) %>
        <% else %>
            <%= select_tag "type", options_for_select([ [t('unsubmitted'), 'unsubmitted'], [t('submitted'), 'submitted'] ], @type) %>
        <% end %>
      </td>
    </tr>
  </table>
  <button type="submit"><%= t("search") %></button>

  <script type="text/javascript">
      $(function () {
          $.datepicker.setDefaults($.datepicker.regional['<%= I18n.locale %>']);
          $("#searchform input[type='date']").datepicker({ dateFormat: 'yy-mm-dd' });
      });
  </script>
</form>
<h1><%= t('search_results') %></h1>

<div id="pagination">

</div>

<div class="clear"></div>

<table id="formList">
  <thead>
  <tr>
    <th>
      <%= t('nest_id', scope: [:activerecord, :attributes, :visitation_form]) %>
    </th>
    <th>
      <%= t('nest', scope: [:activerecord, :attributes, :visitation_form]) %>
    </th>
    <th>
      <%= t('visit_date', scope: [:activerecord, :attributes, :visitation_form]) %>
    </th>
    <th>
      <%= t('photographer_name', scope: [:activerecord, :attributes, :visitation_form]) %>
    </th>

    <% if @visitation_forms.count > 0 %>
        <th></th>
        <th></th>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% @visitation_forms.each do |visitation_form| %>

      <tr>
        <td class="nestid"><%= visitation_form.nest_id  %></td>
        <td class="nestname"><%= visitation_form.nest %></td>
        <td class="visitdate"><%= visitation_form.visit_date.strftime("%d.%m.%Y")  unless visitation_form.visit_date.nil?  %></td>
        <td class="photographer"><%= visitation_form.photographer_name %></td>
        <td><%= link_to t('show'), visitation_form %></td>
        <% if @type.nil? || @type == "unsubmitted" %>
            <td><%= link_to t('edit'), edit_visitation_form_path(visitation_form) %></td>
        <% else %>
            <td></td>
        <% end %>
      </tr>

  <% end %>
  </tbody>
</table>

<script>
    $("#speciesid").autocomplete({
        source: function (request, response) {
            $.ajax({
                url: "<%= url_for(action:"getspecies", controller:"api") %>.json?filter=" + request.term,
                success: function (data) {
                    if (data.species != '') {
                        response($.map(data.species, function (item) {
                            return {
                                label: item.name[0].content + " (" + item.id + ")",
                                value: item.id
                            }
                        }));
                    }
                }
            });
        },
        minLength: 1
    });
</script>

app/views/visitation_forms/show.html.erb
<% if notice %>
    <div id="error_explanation"><h2><%= notice %></h2></div>
<% end %>

<div id="form-status-div">
      <%= t('form_status') %>
      <% if @visitation_form.approved %>
          <%= t('form_already_approved') %>
      <% elsif @visitation_form.sent %>
          <%= t('form_already_sent') %>
      <% else %>
          <%= t('form_not_sent') %>
      <% end %>
</div>

<div>
    <% if @visitation_form.approved %>

    <% elsif @visitation_form.sent %>
        <%= link_to t('unsubmit_visitation_form'), "unsubmit/" + @visitation_form.id.to_s, class: "button-link" %>
    <% else %>
        <%= link_to t('edit'), edit_visitation_form_path(@visitation_form), class: "button-link" %>
        <%= link_to t('delete'), destroy_visitation_form_url(@visitation_form), class: "button-link delete" %>
        <%= link_to t('submit_visitation_form'), "submit/" + @visitation_form.id.to_s, class: "button-link" %>
    <% end %>

    <% if @user[:type] == 'admin' && !@visitation_form.approved %>
        <%= link_to t('approve_visitation_form'), { action: "approve_form" }, class: "button-link" %>
    <% end %>
</div>


<div class="log">
    <h2><%= t('form_history') %></h2>
    <table>
      <% @visitation_form.audit_log_entries.order(:timestamp).reverse_each do |entry| %>
          <tr><td><%= entry.timestamp.strftime("%d.%m.%Y %H:%M")  %></td><td><%= entry.userid %></td><td><%= t('log_' + entry.operation) %></td></tr>
      <% end %>
    </table>
</div>


<div class="boxed">
    <h2><%= t('form_owners') %></h2>
    <ul>
    <% @visitation_form.owners.each do |owner| %>
        <li><%= owner.owner_name %></li>
    <% end %>
    </ul>
</div>

<div class="boxed">
    <h2><%= t('visit_info') %></h2>
    <p>
      <table class="info-table">
        <tr>
          <td><strong><%= t('photographer_name', scope: [:activerecord, :attributes, :visitation_form]) %></strong></td>
          <td><%= @visitation_form.photographer_name %></td>
        </tr>
        <tr>
          <td><strong><%= t('visit_date', scope: [:activerecord, :attributes, :visitation_form]) %></strong></td>
          <td><%= @visitation_form.visit_date.strftime("%d.%m.%Y") unless @visitation_form.visit_date.nil? %></td>
        </tr>
      </table>
    </p>
</div>

<div class="boxed">
    <h2><%= t('camera_info') %></h2>
    <p>
      <table class="info-table">
        <tr>
          <td><strong><%= t('camera', scope: [:activerecord, :attributes, :visitation_form]) %></strong></td>
          <td><%= @visitation_form.camera %></td>
        </tr>
        <tr>
          <td><strong><%= t('lens', scope: [:activerecord, :attributes, :visitation_form]) %></strong></td>
          <td><%= @visitation_form.lens %></td>
        </tr>
        <tr>
          <td><strong><%= t('teleconverter', scope: [:activerecord, :attributes, :visitation_form]) %></strong></td>
          <td><%= @visitation_form.teleconverter %></td>
        </tr>
      </table>
    </p>
</div>

<div class="boxed">
    <h2><%= t('nest_info') %></h2>
    <p>
      <table class="info-table">
        <tr>
          <td><strong><%= t('species_id', scope: [:activerecord, :attributes, :visitation_form]) %></strong></td>
          <td>
            <% if !@visitation_form.species_id.nil? && @visitation_form.species_id != "" %>
                <%= @tipuapi.GetSpecies["species"].select{|s| s["id"] == @visitation_form.species_id}[0]["name"].select{|s| s["lang"] == get_userlocaleforapi}[0]["content"] %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td><strong><%= t('nest_id', scope: [:activerecord, :attributes, :visitation_form]) %></strong></td>
          <td><%= @visitation_form.nest_id %></td>
        </tr>
        <tr>
          <td><strong><%= t('nest', scope: [:activerecord, :attributes, :visitation_form]) %></strong></td>
          <td><%= @visitation_form.nest %></td>
        </tr>
        <tr>
          <td><strong><%= t('municipality', scope: [:activerecord, :attributes, :visitation_form]) %></strong></td>
          <td>
            <% municipality = @tipuapi.GetMunicipalities.select do |m| m["id"] == @visitation_form.municipality end %>
            <% # todo currently always shows the Finnish municipality name %>
            <%= municipality[0]["name"][0]["content"] unless municipality[0].nil? %>
          </td>
        </tr>
      </table>
    </p>
</div>

<h1 id="images-header"><%= t('images') %></h1>

<% bird_no = 1 %>
<% @visitation_form.birds.order(:id).each do |bird| %>
    <div class="boxed">
        <h2><%= t('bird') + " " + bird_no.to_s %></h2>
        <p>
          <table class="info-table">
            <tr>
              <td><strong><%= t('gender') %></strong></td>
              <td>
                    <% if !bird.gender.nil? && bird.gender != "" %>
                        <%= @tipuapi.GetGenders["codes"]["code"].select{|s| s["code"] == bird.gender}[0]["desc"].select{|s| s["lang"] == get_userlocaleforapi}[0]["content"] %>
                    <% end %>
              </td>
            </tr>
            <tr>
              <td><strong><%= t('gender_determination_method') %></strong></td>
              <td>
                <% if !bird.gender_determination_method.nil? && bird.gender_determination_method != "" %>
                    <%= @tipuapi.GetGenderDeterminationMethod["codes"]["code"].select{|s| s["code"] == bird.gender_determination_method}[0]["desc"].select{|s| s["lang"] == get_userlocaleforapi}[0]["content"] %>
                <% end %>
              </td>
            </tr>
            <tr>
              <td><strong><%= t('shyness') %></strong></td>
              <td>
                <% if !bird.shyness.nil? && bird.shyness != "" %>
                    <%= @tipuapi.GetShyness["codes"]["code"].select{|s| s["code"] == bird.shyness}[0]["desc"].select{|s| s["lang"] == get_userlocaleforapi}[0]["content"] %>
                <% end %>
              </td>
            </tr>
            <tr>
              <td><strong><%= t('ringed') %></strong></td>
              <td>
                <% if !bird.ringed.nil? && bird.ringed != "" %>
                    <%= @tipuapi.GetRingedStatus["codes"]["code"].select{|s| s["id"] == bird.ringed}[0]["desc"].select{|s| s["lang"] == get_userlocaleforapi}[0]["content"] %>
                <% end %>
              </td>
            </tr>
            <tr>
              <td><strong><%= t('left_ring_code') %></strong></td>
              <td><%= bird.left_ring_code %></td>
            </tr>
            <tr>
              <td><strong><%= t('left_ring_color') %></strong></td>
              <td><%= bird.left_ring_color %></td>
            </tr>
            <tr>
              <td><strong><%= t('right_ring_code') %></strong></td>
              <td><%= bird.right_ring_code %></td>
            </tr>
            <tr>
              <td><strong><%= t('right_ring_color') %></strong></td>
              <td><%= bird.right_ring_color %></td>
            </tr>
          </table>
        </p>

        <% bird.images.reverse_each do |img| %>
            <div class="image">
                <%= img.filename %> <br />
                <%= link_to image_tag( url_for(:controller => 'images', :action => 'thumbnail', :id => img.id) ), { controller: 'images', action: 'show', id: img[:id] }, target: "_blank" %>
            </div>
        <% end %>
      <div class="clear"></div>
    </div>
    <% bird_no += 1 %>
<% end %>

<div class="boxed">
    <h2><%= t('young_images') %></h2>
    <p>
      <% @young_images.reverse_each do |img| %>
          <div class="image">
            <%= img.filename %> <br />
            <%= link_to image_tag( url_for(:controller => 'images', :action => 'thumbnail', :id => img.id) ), { controller: 'images', action: 'show', id: img[:id] }, target: "_blank" %>
          </div>
      <% end %>
      <div class="clear"></div>
    </p>
</div>

<div class="boxed">
    <h2><%= t('landscape_images') %></h2>
    <p>
      <% @landscape_images.reverse_each do |img| %>
          <div class="image">
            <%= img.filename %> <br />
            <%= link_to image_tag( url_for(:controller => 'images', :action => 'thumbnail', :id => img.id) ), { controller: 'images', action: 'show', id: img[:id] }, target: "_blank" %>
          </div>
      <% end %>
      <div class="clear"></div>
    </p>
</div>

<div class="boxed">
    <h2><%= t('nest_images') %></h2>
    <p>
      <% @nest_images.reverse_each do |img| %>
          <div class="image">
            <%= img.filename %> <br />
            <%= link_to image_tag( url_for(:controller => 'images', :action => 'thumbnail', :id => img.id) ), { controller: 'images', action: 'show', id: img[:id] }, target: "_blank" %>
          </div>
      <% end %>
      <div class="clear"></div>
    </p>
</div>

<div class="boxed">
    <p>
      <h2><%= t('additional_info', scope: [:activerecord, :attributes, :visitation_form]) %></h2>
      <%= @visitation_form.additional_info %>
    </p>
</div>

<script>
  $("a.delete").on("click", function() {
     return confirm('<%= t('confirm_delete') %>');
  });
</script>